### ISSUE TITLE
Test from GH

### ISSUE THREAD

**Issue by baptistejamin** [PierreLeGuen/LinuxMemory#10]
Hello. Is this project still maintained?

**Comment by PierreLeGuen** [comment]
Yes, it works perfectly.

**Comment by baptistejamin** [comment]
Perfect

**Comment by PierreLeGuen** [comment]
Ok

**Comment by baptistejamin** [comment]
### Heading

**Test**

_Test_


> Test

- [x] Check the size looks good on the front end
- [ ] Check the image is centered

@PierreLeGuen 

Duplicate of #5
